### ISSUE TITLE
Реализовать базовую логику "Вопросов"

### ISSUE THREAD

**Issue by Vlad104** [Vlad104/goapp#12]
Пользователь будет задавать вопросы, а сервер будет генерировать на них ответы через стронние сервисы на подобии ChatGPT
Для начала сделаем просто http запрос, который будет возвращать шаблонный ответ на все вопросы:

Сделать запрос для получения ответа: POST: /questions

Тело запроса:

```
type CreateQuestionDto struct {
	UserId   pgtype.UUID `json:"userId"` // идентификатор пользователя задавшего вопрос
	Text     string      `json:"text"`   // текст запроса
}
```

Ответ:

```
type AnswerDto struct {
	Text     string      `json:"text"`  // текст ответа
}
```

Структура

QuestionsController.Create    // парсит параметры запроса "/questions"
	-> QuestionService.Create   // вызывает AnswerService для генерации ответа (в будущем будет добавлена логика по сохранению вопросов в базу данных)
		-> AnswerService.Create   // генерирует ответ (создает шаблонную структуру AnswerDto с дефолтной фразой)

**Comment by alexandrgurin25** [comment]
По поводу этого задания нужен созвон
