### ISSUE TITLE
Реализовать сохранение вопросов в бд

### ISSUE THREAD

**Issue by Vlad104** [Vlad104/goapp#15]
Нужно сохранять все вопросы, которые задает пользоватеть.
  Для этого в обработку зарпоса POST /questions нужно добавить шаг с сохранением вопроса в БД.

  Миграцию с созданием таблицы questions я подготовил в ветке "save-questions". Чтобы на нее переключиться, нужно выполнить:

  ```
  git pull origin
  git checkout -t origin/save-questions
  ```

  В src/database/migrations я добавил два файла:
    20230808_create_questions_table.up.sql -- создание таблицы с вопросами
    20230808_create_questions_table.down.sql -- удаление таблицы с вопросами (в случае отката миграции)

  Нужно:

    1) Сделать сущность вопроса

    ```
      type Question struct {
        ID            int64       `json:"id"`
        UserId        pgtype.UUID `json:"userId"`
        Text          string      `json:"text"`
        CreatedAt     string      `json:"createdAt"`
      }
    ```

    2) Реализовать Репозиторий QuestionsRepository с методом Create (по аналогии с UsersRepository)
      В качестве sql запроса использовать

      ```
      err = repo.DataBase.Conn.QueryRow(
        context.Background(),
        `INSERT INTO "questions" (userId, text) VALUES ($1, $2) RETURNING "id"`,
        question.UserID,
        question.Text,
      ).Scan(&id)
      ```

    3) В QuestionsService нужно добавить зависимость QuestionsRepository.
    И в методе Create сделать сохранение входящего вопроса вызвав Create из QuestionsRepository.
    Сохранение вопроса нужно делать перед обращением в сервис ответов.

**Comment by alexandrgurin25** [comment]
![image](https://github.com/Vlad104/goapp/assets/50056232/a4010c88-9ed6-4df7-8b4f-59cc107e9d9b)

**Comment by Vlad104** [comment]
Что-то я в этом не уверен. Лучше всегда обращайся в официальную документацию инструмента https://git-scm.com/docs/git-checkout#Documentation/git-checkout.txt--t
