### ISSUE TITLE
Добавить метод получения количества заданных вопросов

### ISSUE THREAD

**Issue by Vlad104** [Vlad104/goapp#17]
Добавить запрос GET /questions/count

Логика:
	- получить все вопросы (sql запрос `SELECT * FROM "questions"`)
	- посчитать количество полученных элементов
	- вернуть в ответе на запрос число - кол-во заданных вопросов

**Comment by alexandrgurin25** [comment]
Почему мы не везде используем промежуточное ПО, которое реализует проверку прав ? (main.go стр 53-64)

**Comment by Vlad104** [comment]
> Почему мы не везде используем промежуточное ПО, которое реализует проверку прав ? (main.go стр 53-64)

Потому что некоторые запросы доступны без авторизации. Например, запросы, которые не касаются конкретного пользователя, и могут быть выполнены любым человеком.

Пока что у нас упрощенная версия авторизации, в дальнейшем добавим в нее роли. То есть еще будут изменения.
