### ISSUE TITLE
Реализовать ограничение на создание вопросов

### ISSUE THREAD

**Issue by Vlad104** [Vlad104/goapp#19]
Нужно реализовать логику, запрещающую задавать больше 10 вопросов за день.

В какую сторону смотреть:
	- Достать из бд все вопросы (SELECT * FROM "questions")
	- Посчитать кол-во вопросов, за последний день (условие по полю createdAt)
	- Если вопросов больше 10, то возвращать ошибку

**Comment by alexandrgurin25** [comment]
Всем пользователям, или только одному?
