### ISSUE TITLE
Реализовать генерацию токена доступа

### ISSUE THREAD

**Issue by Vlad104** [Vlad104/goapp#8]
При логине надо формировать токен доступа accessToken в котором будет зашифрована информация о пользователе.
При совершении запросов, пользователь будет передавать этот токен. Из токена будет получаться информация о пользователе, на основе этой информации можно будет принять решение о дальнейшей обработке запроса.

Сейчас нужно реализовать только часть с генерацией accessToken.

Для этого, как правил, используется формат JWT: сервер зашифровывает пользовательские данные и передает их клиенту. Клиент при последующих запросах передает эти данные (accessToken), а сервер их расшифровывает и проверяет. При этом расшифровать их может только сервер, то есть подделка со стороны пользователя исключена.

Статья про то, как работает JWT https://ru.hexlet.io/courses/go-web-development/lessons/auth/theory_unit

Тебе нужно подключить пакет https://github.com/golang-jwt/jwt и реализовать логику формирования accessToken из примера https://pkg.go.dev/github.com/golang-jwt/jwt/v5#example-New-Hmac (там tokenString это accessToken).

В качестве полезной нагрузки (jwt.MapClaims в примере) надо добавить два поля: sum - UserId, и iat - время в секундах, когда токен был создан (time.Now() / 1000).

Для подписания нужно использовать секретный ключ (hmacSampleSecret из примера) - задай его в виде произвольной строки в коде (например secret := "secret")

**Comment by alexandrgurin25** [comment]
[](url)
